#
#	Makefile for this SNAP example
#	- modify Makefile.exconfig when creating a new SNAP example
#
#	implements:
#		all (default), clean
#

include ../../../../Makefile.config
include ../../Makefile.config
include Makefile.ex
include ../Makefile.exmain
