#
# Makefile for non-Microsoft compilers
#

all: make-examples

make-scripts:
	$(MAKE) -C drawing
	$(MAKE) -C generators
	$(MAKE) -C wsubsets

clean:
	$(MAKE) clean -C drawing
	$(MAKE) clean -C generators
	$(MAKE) clean -C wsubsets
