#
# Global configuration for YINS makefiles
#

# Override core SNAP library paths (deeper nesting)
CGLIB = ../../../$(GLIB)
CSNAP = ../../../$(SNAP)
CCORE = ../core

# Override example SNAP library paths (deeper nesting)
EXGLIB = ../../../../$(GLIB)
EXSNAP = ../../../../$(SNAP)
EXCORE = ../../core
EXGLIBADV = ../../../../$(GLIBADV)
EXSNAPADV = ../../../../$(SNAPADV)
EXSNAPEXP = ../../../../$(SNAPEXP)
