#
# Global configuration for YINS makefiles
#

# Shared libraries
YINSCORE = ../../core

# Override example SNAP library paths (deeper nesting)
EXGLIB = ../../../../$(GLIB)
EXSNAP = ../../../../$(SNAP)
EXGLIBADV = ../../../../$(GLIBADV)
EXSNAPADV = ../../../../$(SNAPADV)
EXSNAPEXP = ../../../../$(SNAPEXP)
